import re
from pathlib import Path


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    path = repo_root / "utils" / "file_handler.py"
    txt = path.read_text(encoding="utf-8", errors="replace")

    pattern = re.compile(
        r"def cargar_clientes\(username\):\n(?s:.*?)(?=\n\s*def guardar_clientes\()",
        re.M,
    )

    new_lines = [
        "def cargar_clientes(username):",
        '    """',
        "    Carga la lista de clientes. Si no hay datos locales, restaura desde la nube.",
        "    - Con sucursal activa/configurada: descarga snapshot de esa sucursal.",
        "    - En modo global (sin sucursal activa): descarga de todas las sucursales activas y consolida.",
        '    """',
        "    clientes_file = get_user_file_path(username, 'clientes.json')",
        "",
        "    # 1) Local primero",
        "    try:",
        "        if clientes_file.exists():",
        "            with open(clientes_file, 'r', encoding='utf-8') as f:",
        "                clientes = json.load(f)",
        "            if isinstance(clientes, list) and clientes:",
        "                return clientes",
        "    except Exception:",
        "        pass",
        "",
        "    # 2) Snapshot remoto (modo carpeta). Este restore NO encola sync.",
        "    try:",
        "        from utils.api_handler import descargar_snapshot_dispositivo_nube, listar_dispositivos_hijos_remoto",
        "",
        "        usuario_madre = str(resolve_username(username) or '').strip() or str(username or '').strip()",
        "",
        "        def _extract_clientes(payload):",
        "            if not isinstance(payload, dict):",
        "                return None",
        "            data = payload.get('data')",
        "            if isinstance(data, (list, dict)):",
        "                return data",
        "            snap = payload.get('snapshot')",
        "            if isinstance(snap, dict):",
        "                val = snap.get('clientes')",
        "                if isinstance(val, (list, dict)) or val is None:",
        "                    return val",
        "            val2 = payload.get('clientes')",
        "            if isinstance(val2, (list, dict)) or val2 is None:",
        "                return val2",
        "            return None",
        "",
        "        def _resolve_branch_code():",
        "            # a) contexto activo",
        "            try:",
        "                ctx = get_active_branch_context(username) or {}",
        "                code = str(ctx.get('code', '')).strip().upper()",
        "                if code:",
        "                    return code",
        "            except Exception:",
        "                pass",
        "            # b) config_dispositivo",
        "            try:",
        "                cfg_path = get_user_file_path(username, 'config_dispositivo.json')",
        "                if cfg_path.exists():",
        "                    with open(cfg_path, 'r', encoding='utf-8') as f:",
        "                        cfg = json.load(f)",
        "                    if isinstance(cfg, dict):",
        "                        raw = cfg.get('codigo_dispositivo_hijo') or cfg.get('codigo_dispositivo') or cfg.get('codigo_dispositivo_trabajador') or ''",
        "                        code = str(raw or '').strip().upper()",
        "                        if code:",
        "                            return code",
        "            except Exception:",
        "                pass",
        "            # c) si hay 1 sucursal activa en local",
        "            try:",
        "                dh_path = get_user_file_path(username, 'dispositivos_hijos.json')",
        "                if dh_path.exists():",
        "                    with open(dh_path, 'r', encoding='utf-8') as f:",
        "                        dh = json.load(f)",
        "                    if isinstance(dh, list):",
        "                        activos = [d for d in dh if isinstance(d, dict) and str(d.get('estado', 'activo')).strip().lower() != 'bloqueado' and str(d.get('codigo_dispositivo', '')).strip()]",
        "                        if len(activos) == 1:",
        "                            return str(activos[0].get('codigo_dispositivo', '')).strip().upper()",
        "            except Exception:",
        "                pass",
        "            return ''",
        "",
        "        def _load_from_branch_cache(code):",
        "            try:",
        "                branch_dir = get_branch_cache_data_dir(username, code)",
        "                fp = Path(branch_dir) / 'clientes.json'",
        "                if fp.exists():",
        "                    with open(fp, 'r', encoding='utf-8') as f:",
        "                        data_local = json.load(f)",
        "                    if isinstance(data_local, list) and data_local:",
        "                        return data_local",
        "            except Exception:",
        "                pass",
        "            return None",
        "",
        "        branch_code = _resolve_branch_code()",
        "        if branch_code:",
        "            ok, payload, _msg = descargar_snapshot_dispositivo_nube(",
        "                usuario_madre=usuario_madre,",
        "                codigo_dispositivo=str(branch_code).strip().upper(),",
        "                dataset='clientes',",
        "                include_data=True,",
        "            )",
        "            if ok:",
        "                clientes_data = _extract_clientes(payload)",
        "                if clientes_data is not None:",
        "                    try:",
        "                        save_branch_snapshot_datasets(username, branch_code, {'clientes': clientes_data})",
        "                        clear_branch_runtime_caches()",
        "                    except Exception:",
        "                        pass",
        "                    restored = _load_from_branch_cache(branch_code)",
        "                    if restored is not None:",
        "                        return restored",
        "        else:",
        "            ok, devices, _msg = listar_dispositivos_hijos_remoto(usuario_madre)",
        "            if ok and isinstance(devices, list):",
        "                for d in devices:",
        "                    if not isinstance(d, dict):",
        "                        continue",
        "                    if str(d.get('estado', 'activo')).strip().lower() == 'bloqueado':",
        "                        continue",
        "                    code = str(d.get('codigo_dispositivo', '')).strip().upper()",
        "                    if not code:",
        "                        continue",
        "                    ok2, payload2, _msg2 = descargar_snapshot_dispositivo_nube(",
        "                        usuario_madre=usuario_madre,",
        "                        codigo_dispositivo=code,",
        "                        dataset='clientes',",
        "                        include_data=True,",
        "                    )",
        "                    if not ok2:",
        "                        continue",
        "                    clientes_data = _extract_clientes(payload2)",
        "                    if clientes_data is None:",
        "                        continue",
        "                    try:",
        "                        save_branch_snapshot_datasets(username, code, {'clientes': clientes_data})",
        "                    except Exception:",
        "                        pass",
        "",
        "                try:",
        "                    clear_branch_runtime_caches()",
        "                except Exception:",
        "                    pass",
        "",
        "                try:",
        "                    merged = _load_consolidated_branch_list_dataset(username, 'clientes.json')",
        "                    if isinstance(merged, list) and merged:",
        "                        return merged",
        "                except Exception:",
        "                    pass",
        "    except Exception:",
        "        pass",
        "",
        "    # 3) Fallback legacy",
        "    try:",
        "        from utils.api_handler import obtener_clientes_remoto",
        "        clientes_remotos = obtener_clientes_remoto(username)",
        "        if isinstance(clientes_remotos, list) and clientes_remotos:",
        "            guardar_clientes(username, clientes_remotos)",
        "            return clientes_remotos",
        "    except Exception:",
        "        pass",
        "",
        "    return []",
    ]
    new = "\n".join(new_lines) + "\n"

    out, n = pattern.subn(new, txt, count=1)
    if n != 1:
        raise SystemExit(f"No se pudo reemplazar cargar_clientes (matches={n})")

    path.write_text(out, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

